News = [

        { "word": "Breaking News",                  "value": 1},
        { "word": "International",                  "value": 1},
        { "word": "Lastest News",                   "value": 1},
        { "word": "Most Read",                      "value": 1},
        { "word": "Most Watched News",              "value": 1},
        { "word": "Must See",                       "value": 1},
        { "word": "News",                           "value": 2},
        { "word": "Politics",                       "value": 1},
        { "word": "World News",                     "value": 1},
    ]

Commercial = [
        { "word": "Buy",                            "value": 1},
        { "word": "Customer Service",               "value": 1},
        { "word": "New Items",                      "value": 1},
        { "word": "New Product",                    "value": 1},
        { "word": "New Products",                   "value": 1},
        { "word": "Offers",                         "value": 1},
        { "word": "Orders",                         "value": 1},
        { "word": "Popular Products",               "value": 1},
        { "word": "Sale",                           "value": 1},
        { "word": "Sales",                          "value": 1},
        { "word": "Shop by",                        "value": 1},
        { "word": "Shop",                           "value": 1},
        { "word": "Shopping",                       "value": 1},
        { "word": "Top Sellers",                    "value": 1},
    ]

#Presentaciones de productos, tiendas online. 

Entertainment = [
        { "word": "American Football",              "value": 1},
        { "word": "Anime",                          "value": 1},
        { "word": "Animes",                         "value": 1},
        { "word": "Baseball Match",                 "value": 1},
        { "word": "Baseball",                       "value": 1},
        { "word": "Basketball Match",               "value": 1},
        { "word": "Basketball",                     "value": 1},
        { "word": "Caricature",                     "value": 1},
        { "word": "Cartoon",                        "value": 1},
        { "word": "Comedic Monologues",             "value": 1},
        { "word": "Comedy Series",                  "value": 1},
        { "word": "Comedy Show",                    "value": 1},
        { "word": "Concert",                        "value": 1},
        { "word": "Documentaries",                  "value": 1},
        { "word": "Documentary",                    "value": 1},
        { "word": "Draw",                           "value": 1},
        { "word": "Drawing",                        "value": 1},
        { "word": "Entertaiment",                   "value": 1},
        { "word": "Festival",                       "value": 1},
        { "word": "Film",                           "value": 1},
        { "word": "Films",                          "value": 1},
        { "word": "Floor show",                     "value": 1},
        { "word": "Game",                           "value": 1},
        { "word": "Games",                          "value": 1},
        { "word": "Hero",                           "value": 1},
        { "word": "Ice Show",                       "value": 1},
        { "word": "Ice Show",                       "value": 1},
        { "word": "Late Night Show",                "value": 1},
        { "word": "Magic Show",                     "value": 1},
        { "word": "Monologue",                      "value": 1},
        { "word": "Movie",                          "value": 1},
        { "word": "Movies",                         "value": 1},
        { "word": "Multimedia",                     "value": 1},
        { "word": "Music Album",                    "value": 1},
        { "word": "Music",                          "value": 1},
        { "word": "Musical",                        "value": 1},
        { "word": "New Anime",                      "value": 1},
        { "word": "New Character",                  "value": 1},
        { "word": "New Film",                       "value": 1},
        { "word": "New Hero",                       "value": 1},
        { "word": "New Movie",                      "value": 1},
        { "word": "New Movies",                     "value": 1},
        { "word": "New Serie",                      "value": 1},
        { "word": "New Series",                     "value": 1},
        { "word": "Performance",                    "value": 1},
        { "word": "Podcast",                        "value": 1},
        { "word": "Podcasts",                       "value": 1},
        { "word": "Program",                        "value": 1},
        { "word": "Radio Show",                     "value": 1},
        { "word": "Serie",                          "value": 1},
        { "word": "Series",                         "value": 1},
        { "word": "Show",                           "value": 1},
        { "word": "Shows",                          "value": 1},
        { "word": "Soccer Match",                   "value": 1},
        { "word": "Soccer",                         "value": 1},
        { "word": "Song",                           "value": 1},
        { "word": "Sport",                          "value": 1},
        { "word": "Sports",                         "value": 1},
        { "word": "Stream",                         "value": 1},
        { "word": "Streaming",                      "value": 1},
        { "word": "Theater",                        "value": 1},
        { "word": "TV Programmes",                  "value": 1},
        { "word": "TV Show",                        "value": 1},
        { "word": "TV Shows",                       "value": 1},
        { "word": "Videogame",                      "value": 1},
        { "word": "Videogames",                     "value": 1},
        { "word": "Watch Films",                    "value": 1},
        { "word": "Watch Movies",                   "value": 1},
        { "word": "Watch Sports",                   "value": 1},
        { "word": "Watch TV Programmes",            "value": 1},
]